AWSTemplateFormatVersion: 2010-09-09
Description: >-
    This template will use the lambda custom function to apply the S3 public
    bucket controls to an account.

Parameters:
    CustomFunctionOutputKeyName:
        Type: String

Resources:
    BlockPublicS3Buckets:
        Type: Custom::BlockPublicS3Buckets
        Properties:
            ServiceToken:
                Fn::ImportValue: !Ref CustomFunctionOutputKeyName
